name: Windows pip build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: 'windows-2022'

    steps:
    - uses: actions/checkout@v4
    - uses: clonedSemicolon/setup-strace@v11
    - name: Setup build environment
      uses: ilammy/msvc-dev-cmd@v1
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.3'
    - name: Upgrade pip
      run : |
        python -V
        python -m pip install --upgrade pip
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        cache: 'true'
        cache-key-prefix: 'qt-windows-v2'
        version: '6.9.1'
        setup-python: false
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Build
      run: |
        python setup.py build_ext --inplace
    - name: Run tests
      run: |
        set QT_QPA_PLATFORM=minimal
        set VEUSZ_INPLACE_TEST=1

    - name: Upload strace artifacts
      uses: actions/upload-artifact@v4
      with:
        name: strace-logs
        path: strace-logs/
        python tests/runselftest.py
      env:
        VEUSZ_INPLACE_TEST: '1'
        VEUSZ_REMOVE_FROM_ENV: 'QT_PLUGIN_PATH QML2_IMPORT_PATH'
