# Veusz build using PyPI packages on Ubuntu

name: Ubuntu build using pip packages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Enable strace
      uses: clonedSemicolon/setup-strace@v8
    - name: Try manual strace on a test command
      run: |
        echo "📌 Trying manual strace..."
        mkdir -p strace-logs
        strace -tt -f -o strace-logs/manual.log bash -c "echo Hello"
        echo "🧾 Manual strace output:"
        cat strace-logs/manual.log || echo "❌ Failed to create strace log"
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.3'
    - name: Upgrade pip
      run : |
        python -V
        python -m pip install --upgrade pip
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        cache: 'true'
        cache-key-prefix: 'qt-ubuntu-v3'
        version: '6.9.1'
        setup-python: false
    - name: Install Python dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build extensions
      run: |
        python setup.py build_ext --inplace
    - name: Run tests
      env:
        LD_LIBRARY_PATH: ${{ env.QT_ROOT_DIR }}/lib:{{ env.LD_LIBRARY_PATH }}
        QT_QPA_PLATFORM: minimal
        VEUSZ_INPLACE_TEST: 1
      run: |
        tests/runselftest.py

    - name: Upload strace artifacts
      uses: actions/upload-artifact@v4
      with:
        name: strace-logs
        path: strace-logs/
